apiVersion: v2
name: demo-root-charts
description: Frontend and Backend Demo Application
type: application

version: 0.1.2
appVersion: "1.0"

dependencies:
  - name: frontend-chart
    version: 0.1.0
    repository: "file://charts/frontend-release"

  - name: backend-chart
    version: 0.1.0
    repository: "file://charts/backend-release"