apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
data:
  demo.yaml: |
   {
   "no":100,
   "name":"Jiten"
   }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  APP_NAME: "my-application"
  APP_ENV: "production"
  LOG_LEVEL: "info"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-dockercfg
type: kubernetes.io/dockercfg
data:
  .dockercfg: |
    eyJhdXRocyI6eyJodHRwczovL2V4YW1wbGUvdjEvIjp7ImF1dGgiOiJvcGVuc2VzYW1lIn19fQo=
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  APP_NAME: Im15LWFwcGxpY2F0aW9uIg==
---
apiVersion: v1
kind: Secret
metadata:
  name: my-tls-secret
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCakNDQWU2Z0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJMk1EZ3pNREEzTWpNeE5Gb1hEVE0yTURneU9EQTNNak14TkZvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTVROCjczN2w1NHBCdjViNUQ2bzMzRi8xY0h3cDNVMmE0M1dmVzExbmdJZWtRbDd2bC9xamRubkxSZnBxeFdkeE5HT0IKQlo3WGRjMUJwZU9neU1ZTDlkZnYzQW9lY2I4cWxKQ0NrSWZ5ZHI5RVBZVHZxWlhpUHU3WGM3QWdFSmxMMHdPZQpNZ3hyMEtiUmNkV2ZyUFRwQ204djJteG0wb0JIOUtFWUdMdjNCV09QQUFnM1JTUlk1d0cxc0NEbkFDYnc0Wm15ClpIMlFRUkpyM3lMZElUcVBieFl2RVRaSGRHcmdqL3FoOW9takZlVDlMSTdacUNXZXJCWkNBOXJ3bVNhMFZyZWIKOWM4TmlHZlBpZ2RubFB1QnNwbnRvcjRpMFBUZ204YUd1QzZXajBLZzc4TEdxUTJOdVpuRkc2bldqempraGMyOAphN1RvTEFDRGo0azBoeTcwdTU4Q0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVcKQkJSSFJQK1JVYXdjSW9iUGNiNmxlSU1xUW1rVjNEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFPTlZnQVJ3NQpadkpodUYwcUdreEprUHNjSXlBZUUzeGVKWStBcHQ0NWdtaElwMGh3bU0wWlI1ZWduNUhlSHFuR3RPWG5YV2ZuCjlKMjE2UVd1U2d2NEFhQkJOSDBCS1hlbzFDQmYrR3JUSWNRaVFtcGFMYXliV215R3REU0tSWjZ4SytqeDZiUFIKT01oNHlLVFBPMVNDNVpabVgvaDloZFhaU1h4Nzh5akVyeUphNmdzVkFUeVE5Unlqa3N3dWxzR3h3Q01MaXE4cgpzbnFEZ21YbmgyUjZWUEpWZ1g4MDY4S1JVV1gydVpZTTd6bTN2eVhWVWJ2eDJnNFY5TzIrenkrUmZaRi9Hd0czCk1sMnArd3U1Rk1VZmRLcVc2WFJrU3FnVEdMa3Z3UWlGT3RiZE13SmVmODg2aG0zaGloVEppZCtKdnJtVmM5T3kKN21KemsvdTBaL2FsZ2c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBeE0zdmZ1WG5pa0cvbHZrUHFqZmNYL1Z3ZkNuZFRacmpkWjliWFdlQWg2UkNYdStYCitxTjJlY3RGK21yRlozRTBZNEVGbnRkMXpVR2w0NkRJeGd2MTErL2NDaDV4dnlxVWtJS1FoL0oydjBROWhPK3AKbGVJKzd0ZHpzQ0FRbVV2VEE1NHlER3ZRcHRGeDFaK3M5T2tLYnkvYWJHYlNnRWYwb1JnWXUvY0ZZNDhBQ0RkRgpKRmpuQWJXd0lPY0FKdkRobWJKa2ZaQkJFbXZmSXQwaE9vOXZGaThSTmtkMGF1Q1ArcUgyaWFNVjVQMHNqdG1vCkpaNnNGa0lEMnZDWkpyUld0NXYxencySVo4K0tCMmVVKzRHeW1lMml2aUxROU9DYnhvYTRMcGFQUXFEdndzYXAKRFkyNW1jVWJxZGFQT09TRnpieHJ0T2dzQUlPUGlUU0hMdlM3bndJREFRQUJBb0lCQUF0SndKWG51K3NiTUZFSgpnaE9DVnJxT1NtQmt5bE84TVpXNmlUUUhUc0Q0OC9HY0RueUt5YTNjc2V2V0dmSi85TUJNVXpVMEtJYVlZRnA1CkMyc0lucFkvSk1EVDFEUmh6ZG1vRTRBb3NSVHhaaEhzNlM0MnB1TnVLaTJNK1ViQnFaM0lnaGhpU3JwMnd1KzgKMDkvTVNoUHNpN3V4L2hycmhhV0R5MDlrc01Od0EzZVQ5dmdzOS9paWpDcEYyOU9WSWxEcVYyMmRtWXNTT0FyWQorTHlOclV5TVZlSG5SR040MkJmR1grNHA1a05ZNnZGNFpJb2pWbHlIQTNMcmZ6SEdNZ3VjcS9QcFFBYjdxMXh0Cm9UNE1SOUR2NDZ0UlVSR3NucmhYL0l1RUVkNm8vcjI2eW1hZUxQT3NjblNGWEdaeFVLRnJxdUVJOXJNU3VIV2kKeW9sZmJya0NnWUVBelZhaW1WRzVMcTF0WWhOOGNZK1pBeVRoMTh1Vkg0NDRNajJ4eDRiemtZV1hCTUxTc2w3NApmS004MXMxbHZocS9TWjZSRDBJbTF0Z2JSOHlZMXpkZHhYV25iNkhMQTU5blNTVG02QjFiOENqTVNBVzFkT2N6Ck5HUkFveStZMjNyNlp6SVVqNzM0SDRKTmp4SE1PcHhRZ3BOaTI0VHBWMTk4b3dYMlIxcVY0cE1DZ1lFQTlWeEoKUGw4T2xRSzZRVlJQWUlYNngxMnUwS3BJamEvTjJuT2o2K0lwelhvbEQ2SzFvL1p3TE9meVFRQkpUTTcvSk1TYgpSaHRqby9IOGd5QlRaQ05wR3BFY1FnaXNzaCtyQ2c0VzNZUHhkeXhNU1VXYktxM2dsekhmVW1RVkduOTRabmJaCkxtVWlRNjNQelZ5OEowU3RJMEVqenpRR05Demg2RldIWVdTdTdrVUNnWUE3M1kxTVMvSkVkSldXYVgzM2tka1gKZkpKSG12Z2dHaE95T2lCeHZwdVdpcThyMlMwYWlldkNVc2t6Q3ZFbHlxQ0ljeTF4bUdUQWNJTUxuTS9XdHpLawpsaGU1eVI3cU1IZ3BjQlBPQ25rNmZIcUthUGV0WEphbUtMQmJvMDNhZDNFMzB2Y0JyVzRBcWJtNUE0UmFkaVpXCjIyZVAvcUVWTXlhZ1ZPV25pZloyOXdLQmdGQWhLbjVuRnVFTk9meTU1dzV6MHZtbkc3OWp6VHdRalI3cG8wQVcKNVdZSW5PL2xTSUxhcWJuUXFpb1dTTm4veEEyaTg3N0tsUmptbjN2SFk5U1JSL0w0THcxVnZlaVNOUTZjbVZVUQprUnhGYUVpSnBlb2pUUFN6d2VZcmIwVHZHa2dFU2xzL2hoZ3FQSElwOWZ5eERnWTBjTmhyZWhjeURUa09MWjlkCi9VOHRBb0dCQU1wNGpMQzBXd1QvcDV5NkNkWFVsK0xFUWlOcjk4Y3dVNVUrYndoQ1ZXWnNsakV6emMxL2Vvc0QKOGdzS3lCZVFKMGZuNktWTjI0Ymc5QzJyTzhpUWY1Kzk2dTVGTzlrK3hVOFhjYUFUclFxUStkWFNxMVJ4RHZWOApSdm4va3lYMGxIN0dXb25TTllkbTcyejdlZHlqdGFacWMwNWpnWFcvdGI1WlFnbzdWREZrCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0t