apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: demo-daemonset
spec:
  selector:
    matchLabels:
      name: demo-daemonset
  template:
    metadata:
      labels:
        name: demo-daemonset
    spec:
      containers:
      - name: demo-container
        image: nginx:alpine